import {createServer} from '../../frontend/node_modules/vite/dist/node/index.js';
import react from '../../frontend/node_modules/@vitejs/plugin-react/dist/index.js';
const root=new URL('../../frontend/',import.meta.url).pathname;
const clips=[{id:'demo-clip-1',title:'示例：一个完整观点',generated_title:'示例：一个完整观点',start_time:10,end_time:42,final_score:.86,recommend_reason:'用于界面核对的示例内容，不是真实项目分析结果。',outline:'示例片段',content:[]},{id:'demo-clip-2',title:'示例：操作方法讲解',start_time:65,end_time:101,final_score:.8,recommend_reason:'用于展示切片卡片的结构。',outline:'示例片段',content:[]}];
for (const c of clips) {c.score=c.final_score;c.clip_metadata={recommend_reason:c.recommend_reason,outline:c.outline,content:c.content};}
const project={id:'ux-demo',name:'界面核对 · 示例项目',status:'completed',video_category:'knowledge',created_at:'2026-09-21T10:00:00Z',updated_at:'2026-09-21T10:00:00Z',total_clips:2,total_collections:1,clips,collections:[]};
const collections=[{id:'demo-collection',name:'示例主题合集',description:'两个片段组成的界面示例',clip_ids:clips.map(c=>c.id),project_id:project.id,collection_type:'ai_recommended',created_at:project.created_at}];
const fixture={name:'readonly-audit-fixtures',configureServer(server){server.middlewares.use('/api',(req,res)=>{res.setHeader('Content-Type','application/json');if(req.method!=='GET'){res.statusCode=405;res.end(JSON.stringify({detail:'界面核对模式：不执行写入或生成任务'}));return;}
const p=new URL(req.url,'http://localhost').pathname;let value={};
if(p==='/v1/projects/')value=[project];else if(p==='/v1/projects/ux-demo')value=project;else if(p.startsWith('/v1/clips'))value={items:clips};else if(p.startsWith('/v1/collections'))value={items:collections};else if(p.includes('video-categories'))value={categories:[{value:'default',label:'默认',name:'默认',icon:'🎬',color:'#666'},{value:'knowledge',label:'知识科普',name:'知识科普',icon:'📚',color:'#666'}],default_category:'default'};else if(p.endsWith('/status'))value={status:'completed',percent:100};else if(p.includes('files')||p.includes('/video')){res.statusCode=404;value={detail:'示例无媒体'};}else if(p.includes('settings'))value={api:{api_keys:{},api_model:'qwen-plus'},processing:{processing_chunk_size:5000,processing_min_score:.7,processing_max_clips:5}};res.end(JSON.stringify(value));});}};
const server=await createServer({root,configFile:false,envFile:false,plugins:[react(),fixture],server:{host:'127.0.0.1',port:3011,strictPort:true},resolve:{alias:{'@':root+'src'}},optimizeDeps:{include:['react','react-dom','antd']}});
await server.listen();console.log('Readonly current UI audit: http://127.0.0.1:3011; fixture data only; no product API writes');
